_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.5
            "5": 0.19.2
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
